(
    {
        "meta": {"status": 200, "msg": "OK"},
        "response": {
            "blog": {
                "admin": True,
                "ask": True,
                "ask_anon": True,
                "ask_page_title": "Ask me anything",
                "asks_allow_media": True,
                "avatar": [
                    {
                        "width": 512,
                        "height": 512,
                        "url": "https://64.media.tumblr.com/b8f595a3430b24734cc20d8ebd4d16dc/a3e8c1512c1f6774-0e/s512x512u_c1/cf04691e40651c1d62e7e733e73a61c2766fafd2.png",
                        "accessories": [],
                    },
                    {
                        "width": 128,
                        "height": 128,
                        "url": "https://64.media.tumblr.com/b8f595a3430b24734cc20d8ebd4d16dc/a3e8c1512c1f6774-0e/s128x128u_c1/5762af1243928a7d3d00164ccb910254a4803c72.png",
                        "accessories": [],
                    },
                    {
                        "width": 96,
                        "height": 96,
                        "url": "https://64.media.tumblr.com/b8f595a3430b24734cc20d8ebd4d16dc/a3e8c1512c1f6774-0e/s96x96u_c1/f674fee72fc8a87ed6ff3ac48be33df7ee125c43.png",
                        "accessories": [],
                    },
                    {
                        "width": 64,
                        "height": 64,
                        "url": "https://64.media.tumblr.com/b8f595a3430b24734cc20d8ebd4d16dc/a3e8c1512c1f6774-0e/s64x64u_c1/37362c45a7a317c727cb00aff4f0f38a08cb592b.png",
                        "accessories": [],
                    },
                ],
                "can_chat": False,
                "can_send_fan_mail": True,
                "can_subscribe": True,
                "description": "a bot that archives emojis from certain blogs<br />(run by @goldstargloww)",
                "drafts": 0,
                "facebook": "N",
                "facebook_opengraph_enabled": "N",
                "followed": True,
                "followers": 59,
                "members": 1,
                "is_blocked_from_primary": False,
                "is_nsfw": False,
                "messages": 2,
                "name": "emoji-archive-bot",
                "posts": 4395,
                "primary": False,
                "queue": 0,
                "share_likes": False,
                "subscribed": False,
                "theme_id": 37310,
                "theme": {
                    "avatar_shape": "circle",
                    "background_color": "#686868",
                    "body_font": "Helvetica Neue",
                    "header_bounds": "",
                    "header_image": "https://assets.tumblr.com/images/default_header/optica_pattern_11.png?_v=4275fa0865b78225d79970023dde05a1",
                    "header_image_focused": "https://assets.tumblr.com/images/default_header/optica_pattern_11_focused_v3.png?_v=4275fa0865b78225d79970023dde05a1",
                    "header_image_poster": "",
                    "header_image_scaled": "https://assets.tumblr.com/images/default_header/optica_pattern_11_focused_v3.png?_v=4275fa0865b78225d79970023dde05a1",
                    "header_stretch": True,
                    "link_color": "#ffcc4d",
                    "show_avatar": True,
                    "show_description": True,
                    "show_header_image": True,
                    "show_title": True,
                    "title_color": "#ffcc4d",
                    "title_font": "Gibson",
                    "title_font_weight": "bold",
                },
                "title": "emoji archive bot",
                "total_posts": 4395,
                "tweet": "N",
                "twitter_enabled": False,
                "twitter_send": False,
                "type": "public",
                "updated": 1755725830,
                "url": "https://www.tumblr.com/blog/view/emoji-archive-bot",
                "uuid": "t:DVqhScry4lK3pg_bI7D84Q",
            },
            "posts": [
                {
                    "type": "text",
                    "is_blocks_post_format": True,
                    "blog_name": "emoji-archive-bot",
                    "blog": {
                        "name": "emoji-archive-bot",
                        "title": "emoji archive bot",
                        "description": "a bot that archives emojis from certain blogs<br />(run by @goldstargloww)",
                        "url": "https://www.tumblr.com/blog/view/emoji-archive-bot",
                        "uuid": "t:DVqhScry4lK3pg_bI7D84Q",
                        "updated": 1755725830,
                        "tumblrmart_accessories": {},
                        "can_show_badges": True,
                    },
                    "id": 792100494899363840,
                    "id_string": "792100494899363840",
                    "is_blazed": False,
                    "is_blaze_pending": False,
                    "can_ignite": False,
                    "can_blaze": False,
                    "post_url": "https://www.tumblr.com/blog/view/emoji-archive-bot/792100494899363840",
                    "parent_post_url": "https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248",
                    "slug": "",
                    "date": "2025-08-17 04:44:57 GMT",
                    "timestamp": 1755405897,
                    "state": "published",
                    "format": "html",
                    "reblog_key": "guZcMvP0",
                    "tags": ["blog: alien-emoji-art", "Tw fire", "Cw fire"],
                    "short_url": "https://tmblr.co/Z_rB5Oh_6pGGuq00",
                    "summary": "Melt down emoji\n\nCw: fire, nuclear plant meltdown",
                    "should_open_in_legacy": False,
                    "recommended_source": None,
                    "recommended_color": None,
                    "followed": True,
                    "liked": False,
                    "note_count": 15,
                    "title": "",
                    "body": '<p><a class="tumblr_blog" href="https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248">alien-emoji-art</a>:</p><blockquote><p>Melt down emoji</p><p><br/></p><p>Cw: fire, nuclear plant meltdown </p><p><br/></p><p><a class="tmblr-truncated-link read_more" href="https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248">Keep reading</a></p></blockquote>',
                    "reblog": {
                        "comment": "",
                        "tree_html": '<p><a class="tumblr_blog" href="https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248">alien-emoji-art</a>:</p><blockquote><p>Melt down emoji</p><p><br></p><p>Cw: fire, nuclear plant meltdown </p><p><br></p><p><a class="tmblr-truncated-link read_more" href="https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248">Keep reading</a></p></blockquote>',
                    },
                    "trail": [
                        {
                            "blog": {
                                "name": "alien-emoji-art",
                                "active": True,
                                "theme": {
                                    "header_full_width": 1280,
                                    "header_full_height": 1280,
                                    "header_focus_width": 1280,
                                    "header_focus_height": 1043,
                                    "avatar_shape": "circle",
                                    "background_color": "#FFFFFF",
                                    "body_font": "Helvetica Neue",
                                    "header_bounds": "118,1280,1161,0",
                                    "header_image": "https://64.media.tumblr.com/adacaf1037ba5ba42ea26e31adeccde5/fb1c37a7eddc8ab2-f9/s1280x1280/6ac86621877e22228f5ffe07f0a1ab10076c4c59.png",
                                    "header_image_focused": "https://64.media.tumblr.com/adacaf1037ba5ba42ea26e31adeccde5/fb1c37a7eddc8ab2-f9/s2048x3072_c0,9219,100000,90703/f27081d99cc576987751b1f93d93b5129378fe13.png",
                                    "header_image_poster": "",
                                    "header_image_scaled": "https://64.media.tumblr.com/adacaf1037ba5ba42ea26e31adeccde5/fb1c37a7eddc8ab2-f9/s2048x3072/23f37d6edfd3d5b97c204c1fce117097d84467b2.png",
                                    "header_stretch": True,
                                    "link_color": "#00B8FF",
                                    "show_avatar": True,
                                    "show_description": True,
                                    "show_header_image": True,
                                    "show_title": True,
                                    "title_color": "#000000",
                                    "title_font": "Gibson",
                                    "title_font_weight": "bold",
                                },
                                "share_likes": False,
                                "share_following": False,
                                "can_be_followed": True,
                            },
                            "post": {"id": "781558780235317248"},
                            "content_raw": '<p>Melt down emoji</p><p><br></p><p>Cw: fire, nuclear plant meltdown </p><p><br></p><p><a class="tmblr-truncated-link read_more" href="https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248">Keep reading</a></p>',
                            "content": '<p>Melt down emoji</p><p><br /></p><p>Cw: fire, nuclear plant meltdown </p><p><br /></p><p><a class="tmblr-truncated-link" href="https://www.tumblr.com/blog/view/alien-emoji-art/781558780235317248">Keep reading</a></p>',
                            "is_root_item": True,
                        }
                    ],
                    "can_like": True,
                    "interactability_reblog": "everyone",
                    "interactability_blaze": "noone",
                    "can_reblog": True,
                    "can_send_in_message": True,
                    "muted": False,
                    "mute_end_timestamp": 0,
                    "can_mute": True,
                    "can_reply": True,
                    "display_avatar": True,
                }
            ],
            "total_posts": 1,
        },
    },
    {
        "Server": "nginx",
        "Date": "Wed, 20 Aug 2025 21:46:04 GMT",
        "Content-Type": "application/json",
        "Transfer-Encoding": "chunked",
        "Connection": "keep-alive",
        "Vary": "Accept-Encoding",
        "X-Rid": "1e102cc60788158825a1047f3ab4bda6",
        "X-Ratelimit-Perday-Limit": "5000",
        "X-Ratelimit-Perday-Remaining": "4406",
        "X-Ratelimit-Perday-Reset": "68700",
        "X-Ratelimit-Perhour-Limit": "1000",
        "X-Ratelimit-Perhour-Remaining": "996",
        "X-Ratelimit-Perhour-Reset": "3044",
        "X-UA-Compatible": "IE=Edge,chrome=1",
        "Content-Encoding": "gzip",
        "Strict-Transport-Security": "max-age=31536000; preload",
        "Alt-Svc": 'h3=":443"; ma=86400',
        "Server-Timing": "a8c-cdn, dc;desc=jfk, cache;desc=BYPASS;dur=62.0",
    },
)
